import './globals.css'
import type {Metadata} from 'next'
import {Cairo} from 'next/font/google'
import {getServerSession} from 'next-auth'
import Logout from "./logout";
import Link from "next/link";

const cairo = Cairo({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'React Demo App',
    description: 'Generated by create next app',
}

export default async function RootLayout({children}: {children: React.ReactNode}) {
    const session = await getServerSession()
    return (
        <html lang="en">
        <body className={cairo.className}>
        {
            session
                ? <Logout />
                : <Link href="/login">Login</Link>
        }
        {children}
        </body>
        </html>
    )
}
